#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys

mknod /dev/null c 1 3
mknod /dev/zero c 1 5
mknod /dev/random c 1 8
mknod /dev/urandom c 1 9

mknod /dev/sda b 8 0
mknod /dev/vda b 254 0

mount -t debugfs none /sys/kernel/debug


mkdir -p /fs
mount /dev/sda /fs || mount /dev/vda /fs
mount_okay=$?

ip addr add 10.1.0.2/24 dev eth0
ip link set dev eth0 up

echo -e '\033[32m'
echo "Welcome, Jongy."
echo "Boot took $(cut -d' ' -f1 /proc/uptime) seconds"
echo "Kernel version:"
cat /proc/version
echo -e '\033[m'

if [ $mount_okay = 0 ]; then
    echo -e "\033[32mFilesystem is mounted at /fs\033[m"

    if [ -f fs/init.sh ]; then
        echo "Running fs/init.sh"
        fs/init.sh
    fi
else
    echo -e "\033[32mFilesystem mount failed\033[m"
fi

exec /bin/sh
